language: python
python:
  - "3.6"      # current default Python on Travis CI 
# setting the environment for python
before_script:
  - ./create-env.sh
  - source setup.sh
# command to run tests
script:
  - pytest
# deactivate the environment after the test
after_script:
  - deactivate
