language: python
python:
  - "3.6"      # current default Python on Travis CI 
# setting the environment for python
install:
  - pip install -r requirements.txt
before_script:
  - SETUP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  - export BREAKINGWS_ROOT=$SETUP_DIR
  - export PYTHONPATH=$BREAKINGWS_ROOT:$PYTHONPATH
# command to run tests
script:
  - pytest

