language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt 
# env variable for python
before_script:
  - SETUP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  - export SPLRAND_ROOT=$SETUP_DIR
  - export PYTHONPATH=$SPLRAND_ROOT:$PYTHONPATH
# command to run tests
script:
  - pytest
